testiumjs/testium-driver-wd

- lib/browser/_matchers.js
- lib/browser/element.js
- lib/browser/evaluate.js
- package.json
- test/integration/console.test.js
- test/integration/cookie.test.js
- test/integration/dialog.test.js
- test/integration/element.test.js
- test/integration/evaluate.test.js
- test/integration/form.test.js
- test/integration/header.test.js
- test/integration/mixin.test.js
- test/integration/navigation.test.js
- test/integration/non_browser.test.js
- test/integration/page_data.test.js
- test/integration/proxy.test.js
- test/integration/ssl.test.js
- test/integration/window.test.js
- test/mini-testium-mocha.js
- test/mixin.js
* Update to latest `eslint-config-groupon`
* Run `eslint --fix` to fix spacing issues
The build is broken until https://github.com/babel/babel-eslint/issues/243 is resolved.
> Run `eslint --fix`

- lib/browser/cookie.js
- test/integration/cookie.test.js
With this setup it passes on phantomjs 2.1 which doesn't actually consider domain optional (or potentially can't handle host headers that contain a port).
> Compatible with phantomjs 2.1

- lib/browser/element.js
- lib/browser/form.js
- package.json
- test/integration/element.test.js
both were in the docs, but not actually implemented:
* `browser.setValue()` (alias for `browser.clearAndType()`)
* `browser.assertElementHasAttributes()`
Upgraded `assertive` to support assertions on promises
> feat: add 2 missing methods

- lib/browser/cookie.js
- test/integration/cookie.test.js
* takes `{ [name]: value, ... }` object
* uses `setCookieValue()` under the hood
* supplants `setCookies()` (now deprecated)
> feat: add setCookieValues() method

- lib/browser/cookie.js
The changes for remote browser included defaulting the cookie domain to
browser.defaultCookieDomain, which doesn't work inside a mixed-in wd
method.  This doesn't fix that problem, but makes the basic cookie code
at least work again for validating browsers (e.g. phantomjs 2.x)
See: https://github.com/testiumjs/testium-driver-wd/issues/19
> fix: fallback default for setCookieValue

- lib/testium-driver-wd.js
- test/integration/navigation.test.js
* passes thru to navigateTo
* defaults to equiv of `.assertStatusCode(200)`
* accepts in options `{ expectedStatusCode: Number|RegExp|Function }`
> feat: add browser.loadPage as better navigateTo

- .testiumrc
- lib/testium-driver-wd.js
- package.json
- test/integration/mixin.test.js
- test/test-mixin-module/index.js
- test/test-mixin-module/package.json
Per the docs:
> Each setting is an array of module names that will be resolved
> relative to the working directory. E.g. `./test/mixins/session.js` will
> be resolved to `${cwd}/test/mixins/session.js` and `mixins/session` may be
> resolved to `${cwd}/node_modules/mixins/session.js`.
That wasn't true before this, but since some people may depend on the
old behavior to put something like `test/some-file`, we first check for
working local path, then try prepending node_modules.
> fix: support `mixins.wd[] = 'some-module'`

- .travis.yml
- lib/testium-driver-wd.js
- package.json
We use bluebird, wd uses q - both support long stack traces.  Our
current stack traces are fairly useless - this lets you at least see
which test file the error happened in
before:
```
not ok 2 App responds with 200
Error: Assertion failed: statusCode
Expected: 200
Actually: 302
at error (node_modules/testium-driver-wd/node_modules/assertive/lib/assertive.js:103:10)
at equal (node_modules/testium-driver-wd/node_modules/assertive/lib/assertive.js:299:13)
at Object._oneTest [as equal] (node_modules/testium-driver-wd/node_modules/assertive/lib/assertive.js:533:15)
at compareTo (node_modules/testium-driver-wd/lib/browser/cookie.js:101:14)
at _fulfilled (node_modules/wd/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (node_modules/wd/node_modules/q/q.js:863:30)
at …
```
> feat: show long stack traces on errors

- lib/browser/_asserters.js
- lib/browser/element.js
- test/integration/element.test.js
One of the most common needs to drop to `.then()` we've seen is people
checking the number of matched elements present - might as well make it
a supported assertion.
> feat: browser.assertElementsNumber(selector, num)

- lib/testium-driver-wd.js
`loadPage()` had a typo which was leaking `expectedStatusCode` into the
options passed to `navigateTo()`
> fix: don't pass expectedStatusCode thru as option

- lib/testium-driver-wd.js
- package.json
- test/integration/header.test.js
- test/mini-testium-mocha.js
To aid in determining which requests to your SOA stack are which, sets a
default X-Request-Id header, with (if available), the currentTest
property supplied by testium-mocha@>=2.1.1 and a v1 UUID
This will be usable once https://github.com/testiumjs/testium-mocha/pull/13 ships
> generate a default X-Request-Id header

- lib/testium-driver-wd.js
before we were just passing the browser, but `testium-core` mixes the
browser into the proper spot in `desiredCapabilities` anyway, so now we
get all of them
> use all `desiredCapabilities` in driver

- lib/testium-driver-wd.js
> feat: expose getChromeDevtoolsPort method

- .travis.yml
- lib/testium-driver-wd.js
- package.json
- test/integration/puppeteer.test.js
This will expose a `browser.withPuppeteerPage()` API that can be used to access all puppeteer page APIs. It's now also possible to run lighthouse reports using `browser.getLighthouseData()`.
The lighthouse method takes the active URL, opens a new tab, and then reloads a bunch of times. This behavior is part of lighthouse.
---
_This PR was started by: [git wf pr](https://github.groupondev.com/InteractionTier/workflow-cli/releases/tag/v1.7.0)_
> Add puppeteer and lighthouse integration

- lib/browser/lighthouse.js
- lib/lighthouse.js
- lib/testium-driver-wd.js
**Purpose:**
Currently testium has an lighthouse API `getLighthouseData` which calls _lighthouse_ method and returns the response. Having additional APIs like `assertLighthouseScore()` or returning the parsed results,  would make the audits easy to integrate and use.
**Scope:**
This PR exposes above 2 APIs which can be consumed in either of following ways -
```
context('Accessibility Tests version 1', () => {
let lhResults;
before(() =>
browser
.login('some-user')
.loadPage('/some-page')
.runLighthouseAudit()
.then(audit => {lhResults = audit;})
);
after(() => browser.clearCookies());
it(`checking for score over 85`, () => 
assert.expect(`score is only ${lhResults.score}`, lhResults.isSuccess(85))
);
it(`There are no errors`, () => 
assert.expect(lhResults.errorString(), …
```
> feat: Add supporting APIs for lighthouse

- lib/browser/lighthouse.js
- lib/testium-driver-wd.js
- move `accesskeys` from manual audit (https://github.com/GoogleChrome/lighthouse/pull/7129)
- pass default score (100) for assertion
- Support `accessibilityChecks` and `accessibilityScore` optional items to be under `options`
**Sample Call**
```
before(() =>
browser.loadPage('/path', { accessibilityChecks: true })
);
```
**Screenshot**  (failure case) -
> feat: optional accessibility check with loadPage

- lib/testium-driver-wd.js
Follow up PR from - https://github.com/testiumjs/testium-driver-wd/pull/43
Lighthouse runs audit in responsive mode by default, so we must pass flags through `loadPage` to also support desktop.
For Mobile browsers -
```
browser.loadPage('/path', {
headers: { 'X-Client-Platform': 'touch' },
accessibilityChecks: true
})
```
For Desktop browsers -
```
browser.loadPage('/path', {
accessibilityChecks: true,
flags: { chromeFlags: ['--disable-device-emulation']}
})
```
Note: 
Though, it seemed intuitive to run accessibility audit along with `loadPage` call, it might be overhead to pass extra info in options. Possibly if we can find better way to identify the device and run audit accordingly (looking at the header?)
> fix: pass flags to lighthouse audit from loadPage

- .eslintrc
- .travis.yml
- lib/browser/lighthouse.js
- test/integration/lighthouse.test.js
- test/integration/puppeteer.test.js
```js
browser.a11yAudit()
browser.a11yAudit({ ignore: ['document-title'], flags, config })
```
returns
```js
[
{
"auditId": "document-title",
"description": "Ensures each HTML document contains a non-empty <title> element",
"snippet": "<html>",
"impact": "serious",
"help": "Documents must have <title> element to aid in navigation",
"helpUrl": "https://dequeuniversity.com/rules/axe/3.1/document-title?application=axeAPI",
"tags": ["cat.text-alternatives", "wcag2a", "wcag242"],
"selector": "html",
"path": "1,HTML"
},
{
"auditId": "html-has-lang",
"description": "Ensures every HTML document has a lang attribute",
"snippet": "<html>",
"impact": "serious",
"help": "<html> element must have a lang attribute",
"helpUrl": "https://dequeuniversity.com/rules/axe/3.1/html-has-lang?application=axeAPI", …
```
> feat: new a11yAudit function

- lib/browser/navigation.js
- test/integration/navigation.test.js
> feat: browser.getUrlObj()

- lib/browser/lighthouse.js
Some of lighthouse's audits have details, but not a details.items, so when the previous line would check for details.items.length it would automatically fail, making browser.runLighthouseAudit unusable.
> Lighthouse audit details fix
